[libraries]
# androidx - Jetpack libraries
# https://developer.android.com/jetpack/androidx/versions
androidx-core = { module = "androidx.core:core", version = "1.13.1" }
androidx-sqlite = { module = "androidx.sqlite:sqlite", version = "2.4.0" }