name: CI
on:
  - pull_request
  - push
  - workflow_dispatch


env:
  JDK_VERSION: "23"


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: ${{ env.JDK_VERSION }}

      - name: Accept Android SDK Licenses
        shell: bash
        run: yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses || true

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Gradle Check
        run: ./gradlew check allDevicesCheck --info -S --show-version